### ISSUE TITLE
服务端启动一直显示正在启动中

### ISSUE THREAD

**Issue by jeanpg** [Casual-Ragnarok/ro-single-server#111]
启动架构bat，一直显示正在启动中，无法执行到后面已经正常启动

**Comment by jeanpg** [comment]
> 无法登录正常启动Ro服务端bat 脚本，提示账号密码不正确

**Comment by kangtianyu** [comment]
Start MySQL server not success
The code is 
start /MIN \usr\local\mysql\bin\mysqld-opt.exe --defaults-file=/usr/local/mysql/my.cnf

buy no my.cnf existed

**Comment by AllenHsiu** [comment]
這個my.cnf是要哪裡有得載啊? 最新的zip file裡面沒有

**Comment by CasualRO** [comment]
已修复：
https://github.com/Casual-Ragnarok/ro-single-server/commit/14ce20cc30cf248f94e6725ad2af4ccd85a791b5
https://github.com/Casual-Ragnarok/ro-single-server/commit/77be54316946a11babec024924bfafab6c388e83
