### ISSUE TITLE
人物無法觸發傳送點地圖切換，地圖無 NPC（因為編碼無法載入npc設定檔，已解決）

### ISSUE THREAD

**Issue by danielhuang-030** [Casual-Ragnarok/ro-single-server#112]
你好，感謝分享讓我有機會重溫最粗的感動～
server 端跟 client 端都正常運行
創建角色也沒有問題
但是進入遊戲後無法觸發傳送點地圖切換
GM @warp 指令可以運作，但傳送到其他地圖後好像也沒有看到 NPC 的人物只有圖示
![image](https://user-images.githubusercontent.com/17424415/192078988-5dcc1c7d-3476-4f25-ba4b-0c339b18a1b9.png)

找到問題點了，應該是因為編碼，系統找不到 npc 設定的關係；只有在非簡體中文的環境會發生
![image](https://user-images.githubusercontent.com/17424415/192095657-2f66f262-6912-4b11-a843-f18956003b54.png)

解決方式：
- 安裝 Locale Emulator
- 依序使用簡中環境，開啟 char-server.exe > login-server.exe > map-server.exe
![image](https://user-images.githubusercontent.com/17424415/192099277-ce41d6df-27f7-451b-a456-987a7bf92a9d.png)
- cmd 仍會是亂碼，不過 npc 設定檔已經可以正確被載入
![image](https://user-images.githubusercontent.com/17424415/192099314-afe283a6-e3c2-4107-a369-77576a036710.png)
- 開啟 client 端進入遊戲，就可以看到 npc 跟傳送點了
![image](https://user-images.githubusercontent.com/17424415/192099377-7d5a307d-246f-49fd-9355-90cae5e43e06.png)

**Comment by jeanpg** [comment]
请问如何正常启动？

**Comment by sixcats** [comment]
用了解码还是没有npc和地图切换

**Comment by sixcats** [comment]
![Uploading 42f12806-ae2d-4f0e-b6cf-68484f8c4ebe.png…]()
