### ISSUE TITLE
map-server.exe报病毒,且错误0xC000007b无法启动

### ISSUE THREAD

**Issue by Nephits** [Casual-Ragnarok/ro-single-server#113]
map-server.exe被WindowsDefender报病毒...请确认
Windows 10Pro JP 22H2
为防万一我采用Hyper-V虚拟机运行本程序.

运行后,错误0xC000007b无法启动
https://rathena.org/board/topic/113773-map-serverexe-unable-to-start-0xc000007b/
这里显示是MSVCR110.DLL的问题,但换了数个版本的MSVCR110.DLL仍无改善

**Comment by CasualRO** [comment]
README 写了你不看？

```
运行服务端报错： 0xc000007b
缺失 DirectX 或版本过旧导致，

修复包： DirectXRepair-v3.9 【[百度网盘(vs1m)](https://pan.baidu.com/s/1zoBXTi5rp7Yj1bhzMzo-oQ)】 (如果可以直接运行就不用装了)
```

没备案的程序都会报毒，你信杀软误报不玩就是，没人强迫你
