### ISSUE TITLE
启动架设环境bat闪退不运行 + 已解决方案

### ISSUE THREAD

**Issue by mingyzeyuan** [Casual-Ragnarok/ro-single-server#115]
java和visual c++运行环境我都齐全
并且02-启动服务器bat可以运行虽然会报错
而01bat直接闪退没有报错
我查看01bat的内容，把涉及到的所有exe文件都设置为使用administrator运行，依然不行

**Comment by mingyzeyuan** [comment]
bat末尾加pause后bat依然没有任何运行，窗口直接关闭，没有任何报错

**Comment by mingyzeyuan** [comment]
通过cmd运行bat文件有如下warning
C:\Users\Ming>cd /d J:\ROSPPCN\rosingleservermaster

J:\ROSPPCN\rosingleservermaster>01-启动架设环境.bat

J:\ROSPPCN\rosingleservermaster>n multi-Apache servers on same PC. Apache 2.2.9 core
'n' is not recognized as an internal or external command,
operable program or batch file.

J:\ROSPPCN\rosingleservermaster>##############
'##############' is not recognized as an internal or external command,
operable program or batch file.

J:\ROSPPCN\rosingleservermaster>Emulator\usr\local\apache2\logs\httpd.pid goto :NOTSTARTED
The system cannot find the path specified.

J:\ROSPPCN\rosingleservermaster>cp   | FIND /I " "  1>NUL
'cp' is not recognized as an internal or external command,
operable program or batch file.

J:\ROSPPCN\rosingleservermaster>

似乎执行时不能正确分行？把命令的一部分砍掉读取了

**Comment by mingyzeyuan** [comment]
用powershell打开01-docker。。。ps1有如下warning
PS J:\ROSPPCN\rosingleservermaster> .\01-Run_Env_Docker.ps1
docker-compose : The term 'docker-compose' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At J:\ROSPPCN\rosingleservermaster\01-Run_Env_Docker.ps1:1 char:1
+ docker-compose up -d
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker-compose:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mingyzeyuan** [comment]
OK，把虚拟机里的三个bat文件和my.cnf拖出来，终于可以在本机上使用了。

**Comment by s98082154** [comment]
我也遇到"启动架设环境bat闪退不运行"

請問要怎麼解決?

**Comment by s98082154** [comment]
> OK，把虛擬機裡的三個bat文件和my.cnf拖出來，終於可以在本機上使用了。

這部分可以說明怎麼操作嗎?

**Comment by mingyzeyuan** [comment]
> > OK，把虛擬機裡的三個bat文件和my.cnf拖出來，終於可以在本機上使用了。
> 
> 這部分可以說明怎麼操作嗎?

下载那个标着“vmware永久激活版”的链接，下载vmware（注意这里要正式版，免费版不能设置port forwarding），运行虚拟机，设置好port forwarding。如果你接受在虚拟机里开服务器，那不需要额外操作了，而且已经激活好了。只是虚拟机占用资源可能稍微多一点。
如果还想在本机运行server，那么
找到虚拟机里面对应的这三个文件，文件名不太一样，是
1.启动架设环境
2.启动99maxeathena三转（复兴和）
3.关闭架设环境

虚拟机里的文件可以正常复制，然后在你桌面粘贴就好。
再就是虚拟机里的my.inf也要复制出来
路径大概是在emulator/usr/local/mysql
再放在你本机这个文件夹下。

**Comment by mingyzeyuan** [comment]
> 下载vmware（注意这里要正式版，免费版不能设置port forwarding）

如果你不想在虚拟机里运行客户端，只想要复制那几个文件出来，那不需要正式版，免费版vmware也可以打开文件复制文件。

**Comment by s98082154** [comment]
> > > OK，把虛擬機裡的三個bat文件和my.cnf拖出來，終於可以在本機上使用了。
> > 
> > 
> > 這部分可以說明怎麼操作嗎?
> 
> 下载那个标着“vmware永久激活版”的链接，下载vmware（注意这里要正式版，免费版不能设置port forwarding），运行虚拟机，设置好port forwarding。如果你接受在虚拟机里开服务器，那不需要额外操作了，而且已经激活好了。只是虚拟机占用资源可能稍微多一点。 如果还想在本机运行server，那么 找到虚拟机里面对应的这三个文件，文件名不太一样，是 1.启动架设环境 2.启动99maxeathena三转（复兴后） 3.关闭架设环境
> 
> 虚拟机里的文件可以正常复制，然后在你桌面粘贴就好。 再就是虚拟机里的my.inf也要复制出来 路径大概是在emulator/usr/local/mysql 再放在你本机这个文件夹下。

謝謝~我再試試看

**Comment by xiw3n** [comment]
hello, 我想本机运行，又不想下10+G的虚拟机，可否直接分享这几个文件？

**Comment by mingyzeyuan** [comment]
> 1.启动架设环境
> 2.启动99maxeathena三转（复兴后）
> 3.关闭架设环境

https://github.com/mingyzeyuan/rospfile

**Comment by xiw3n** [comment]
hi大佬，这几个文件下载放入服务端文件夹后，点击打开仍然闪退，原因是啥？

**Comment by mingyzeyuan** [comment]
那可就真不知道了。说白了之前到底为什么闪退也没搞清楚，只是换了文件就能用了而已

**Comment by mingyzeyuan** [comment]
> hi大佬，环境启动成功了（不过只有4行，不是7行，也提示成功了），mapserv和logserv提示: 无法使用您提供的 MySQL访问账号='root'; charsev提示在mysql丢失数据表。。。下一步该怎么处理？

那你应该是那个my.inf文件没有放对地方

**Comment by xiw3n** [comment]
> > hi大佬，环境启动成功了（不过只有4行，不是7行，也提示成功了），mapserv和logserv提示: 无法使用您提供的 MySQL访问账号='root'; charsev提示在mysql丢失数据表。。。下一步该怎么处理？
> 
> 那你应该是那个my.inf文件没有放对地方

端口占用，关掉就好了。现在的问题是，选服务器画面后，下一步就闪退了。。。

**Comment by mingyzeyuan** [comment]
客户端那闪退的原因就更多了。。。重新注册一个账户试试

**Comment by AllenHsiu** [comment]
有人可以提供repo 缺失的my.cnf 嗎?

**Comment by mingyzeyuan** [comment]
> 有人可以提供repo 缺失的my.cnf 嗎?

点我id看我repository

**Comment by CasualRO** [comment]
https://github.com/Casual-Ragnarok/ro-single-server/commit/14ce20cc30cf248f94e6725ad2af4ccd85a791b5

统一回答下，bat 脚本闪退是因为我最后一次修改是在 mac 环境导致换行符变成了 LF ， 已经改回 win 换行符 CRLF
