### ISSUE TITLE
无法通过地址访问数据库

### ISSUE THREAD

**Issue by mingyzeyuan** [Casual-Ragnarok/ro-single-server#116]
浏览器内使用localhost/phpmyadmin 或者 127.0.0.1:3306都无法访问数据库，不是不能登录而是直接invalid response
1-启动环境里边的server后边有显示127.0.0.1：8096的地址，而mysql那一行后边则没有显示地址。
servers可以正常启动也显示已经访问了127.0.0.1的数据库。
使用gui工具设置访问127.0.0.1:3306, navicat可以访问 mysql workbench则不行

我也尝试了用laragon来搭建这个数据库，数据库倒是可以载入和访问了，但是server又没法用bat启动。还在继续尝试。

**Comment by CasualRO** [comment]
此版本只在桌面版测过，win server 会存在其他问题需要自己解决的。
例如一键启动 mysql 起不来，你只能在一键启动脚本中把 mysql 注释掉，然后自己搭建一个独立 mysql 把数据文件迁移过去。

你说的 bat 无法启动原因是版本比较旧的 win 无法识别 linux 的换行符导致的，我最后一次更新是用 mac 上传的，所以没留意到换行符有问题，这问题已修正。
