### ISSUE TITLE
map server 檔案缺失 導致無法開啟

### ISSUE THREAD

**Issue by AllenHsiu** [Casual-Ragnarok/ro-single-server#120]
map server 執行時會說這些檔案缺失 但檢查過檔案明明都有

<img width="1030" alt="Screenshot 2023-10-03 at 1 38 02 PM" src="https://github.com/Casual-Ragnarok/ro-single-server/assets/26738143/d86d490f-6b2a-4fc4-9c80-550f899887fa">

**Comment by CasualRO** [comment]
参考这里 https://github.com/Casual-Ragnarok/ro-single-server/issues/112
