### ISSUE TITLE
我服了，各种闪退，一个坑没落下，全踩了

### ISSUE THREAD

**Issue by zxx68688** [Casual-Ragnarok/ro-single-server#121]
先是.bat文件读取顺序不对，必须重新复制到自己电脑在弄到服务器里，然后缺少my.cnf文件，找半天在聊天记录找到了，弄好了之后客户端又闪退，吐了

**Comment by cmtomkan310** [comment]
客户端闪退，你到了选择服务哪里，闪退的把？解决了吗？

**Comment by CasualRO** [comment]
已修复：
https://github.com/Casual-Ragnarok/ro-single-server/commit/14ce20cc30cf248f94e6725ad2af4ccd85a791b5
https://github.com/Casual-Ragnarok/ro-single-server/commit/77be54316946a11babec024924bfafab6c388e83
