### ISSUE TITLE
请问，这套配置下，openkore中的参数是什么？

### ISSUE THREAD

**Issue by areur3ady** [Casual-Ragnarok/ro-single-server#123]
serverType 
serverEncoding 
charBlockSize 
addTableFolders

**Comment by CasualRO** [comment]
通用配置，没有任何封包 key

**Comment by areur3ady** [comment]
您好，能否给一个针对这个版本服务器和客户端的配置样板，跟着https://exp-blog.com/game/ro/openkore-bi-ji-ru-men-pian/#toc-heading-3 这个教程操作一通，还是失败无法extract出serverType。

网上检索了一圈，感觉可能是single-client中的exe文件不是官方原版。

请问Packet Tokenizer: Unknown switch: 0AC4报错是什么原因导致的？

ref：https://github.com/OpenKore/openkore/issues/3726

**Comment by 2064561677** [comment]
试试这个设置
[localHost - rA/Herc 2018]
ip 127.0.0.1
port 6900
master_version 1
version 28
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/RagexeRE_2018_04_04b;iRO
charBlockSize 155
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1
我成功了
